leaf/blueprints/admin.py
from flask import Blueprint, render_template, url_for, redirect, flash, abort
from leaf.models import User
from leaf.ext import db
from flask_login import login_required, current_user
from leaf.decorators import confirm_required


admin = Blueprint("admin", __name__)

# 查看用户详情页
@admin.route("/profile/<string:user_name>")
@login_required
def profile(user_name):
    user = User.query.filter_by(name=user_name).first()
    if user:
        return render_template("/admin/profile.html", user=user)
    else:
        abort(404)


# 用户管理
@admin.route("/manage-users")
@login_required
@confirm_required
def manage_users():

    if not current_user.is_admin:
        flash("后台管理功能只对系统管理员开放", "warning")
        return redirect(url_for("main.index"))

    users = User.query.order_by(User.signup_time.desc()).all()
    return render_template("admin/manage_users.html", users=users)


# 封禁/解封用户
@admin.route("/toggle-user/<string:user_name>", methods=["POST", "GET"])
@login_required
@confirm_required
def toggle_block_user(user_name):

    if not current_user.is_admin:
        flash("后台管理功能只对系统管理员开放", "warning")
        return redirect(url_for("main.index"))

    user = User.query.filter_by(name=user_name).first()
    user_status = user.is_blocked
    user.is_blocked = not user_status
    db.session.commit()
    return redirect(url_for("admin.manage_users"))

leaf/blueprints/main.py
from flask import Blueprint, render_template, url_for, redirect, abort, flash, request, current_app, send_from_directory
from leaf.forms import ProjectForm, UploadForm, ChooseMemberForm, ChangeProjectForm, ChangeFileForm, ConfirmDeleteForm
from leaf.ext import db
from leaf.models import Project, File, User
from flask_login import login_required, current_user, fresh_login_required
from leaf.decorators import confirm_required
from leaf.utils import redirect_back
import os, uuid
from leaf.emails import send_add_new_member_email, send_upload_file_email

main = Blueprint("main", __name__)


# 网站首页
@main.route("/", methods=["GET", "POST"])
def index():
    latest_project = Project.query.order_by(Project.create_time.desc()).first()
    latest_file = File.query.order_by(File.upload_time.desc()).first()
    projects_sum = Project.query.count()
    files_sum = File.query.count()
    users_sum = User.query.count()

    return render_template("main/index.html",
                           files_sum=files_sum,
                           projects_sum=projects_sum,
                           users_sum=users_sum,
                           latest_project=latest_project,
                           latest_file=latest_file
                           )


# 显示所有项目列表
@main.route("/allprojects", methods=["GET", "POST"])
@login_required
@confirm_required
def show_all_projects():
    projects = Project.query.order_by(Project.create_time.desc()).all()
    return render_template("main/show_all_projects.html", projects=projects)


# 创建新项目
@main.route("/create", methods=["GET", "POST"])
@login_required
@confirm_required
def create_project():
    form = ProjectForm()
    if form.validate_on_submit():
        name = form.name.data
        description = form.description.data
        start_time = form.start_time.data
        end_time = form.end_time.data
        new_project = Project(
            name=name,
            description=description,
            start_time=start_time,
            end_time=end_time,
            its_creator = current_user._get_current_object()
        )
        new_project.its_member_users.append(current_user._get_current_object())
        db.session.add(new_project)
        db.session.commit()
        # return redirect(url_for("main.show_all_projects"))
        return redirect( url_for("main.add_user", project_id=new_project.id ) )
    return render_template("main/create_project.html", form=form)


# "我的上传"
@main.route("/my_uploads", methods=["GET", "POST"])
@login_required
@confirm_required
def my_uploads():
    files = User.query.filter_by(name=current_user.name).first().its_upload_files
    return render_template("main/my_uploads.html", files=files)


# 上传文件
@main.route("/upload/<project_id>", methods=["GET", "POST"])
@login_required
@confirm_required
def upload(project_id):
    project = Project.query.filter_by(id=project_id).first()
    if project:
        form = UploadForm()

        if form.validate_on_submit():
            file = form.file.data
            origin_filename = str(file.filename)
            secure_filename = str(uuid.uuid1())
            # file_size = len(file.read())
            description = form.description.data
            author = form.author.data
            reviewer = form.reviewer.data
            file.save(os.path.join(current_app.config['UPLOAD_PATH'], secure_filename))
            file_size = int(os.path.getsize(os.path.join(current_app.config['UPLOAD_PATH'], secure_filename)))
            file =File(
                secure_filename=secure_filename,
                origin_filename=origin_filename,
                file_size=file_size,
                description=description,
                author=author,
                reviewer=reviewer
            )

            file.its_uploader = current_user._get_current_object()
            file.its_project = project

            db.session.add(file)
            db.session.commit()

            # 自动将文件上传消息邮件通知给项目组其他成员
            to_email_list = []
            for item in project.its_member_users:
                if item.email != current_user.email:
                    to_email_list.append(item.email)
            send_upload_file_email(user=current_user, file=file, to_email_list=to_email_list, to=None)

            flash("文件上传成功", "success")
            return redirect(url_for("main.project_detail", project_id=project_id))

        return render_template("main/upload.html", form=form, project=project)
    else:
        abort(404)


# 查看项目详情页
@main.route("/detail/<project_id>")
@login_required
@confirm_required
def project_detail(project_id):
    project = Project.query.filter_by(id=project_id).first()
    download_path = current_app.config['UPLOAD_PATH'] + '/'
    return render_template("main/project_detail.html", project=project, download_path=download_path)


# 下载文件
@main.route("/download/<file_id>")
@login_required
@confirm_required
def download(file_id):

    file = File.query.filter_by(id=file_id).first()
    # 判断该登录用户是否为项目组成员
    if current_user in file.its_project.its_member_users or current_user.is_admin:
        filename = file.secure_filename
        path = current_app.config['UPLOAD_PATH'] + "/"
        return send_from_directory(path, filename, attachment_filename=file.origin_filename ,as_attachment=True)
    else:
        flash("您还不是项目组成员，无权下载文件", "warning")
        return redirect(url_for("main.project_detail", project_id=file.its_project.id))


# 添加项目成员
@main.route("/adduser/<project_id>", methods=["GET", "POST"])
@login_required
@confirm_required
def add_user(project_id):
    project = Project.query.filter_by(id=project_id).first()
    form = ChooseMemberForm(project=project)
    if form.validate_on_submit():
        choosen_id_list = form.member.data
        to_email_list = []
        for item in choosen_id_list:
            user = User.query.filter_by(id=item).first()
            project.its_member_users.append(user)
            to_email_list.append(user.email)
        db.session.commit()

        # 给被添加的新成员发邮件通知
        send_add_new_member_email(to_email_list=to_email_list, project=project, user=current_user)

        flash("添加成员成功", "success")
        return redirect_back()

    return render_template("main/add_user.html", form=form, project=project)


# 修改项目简介
@main.route("/change-project/<project_id>", methods=["GET", "POST"])
@login_required
def change_project(project_id):
    project = Project.query.filter_by(id=project_id).first()
    form = ChangeProjectForm()

    if form.validate_on_submit():
        if form.new_name.data:
            project.name = form.new_name.data
        if form.new_description.data:
            project.description = form.new_description.data
        if form.new_start_time.data:
            project.start_time = form.new_start_time.data
        if form.new_end_time.data:
            project.end_time = form.new_end_time.data
        db.session.commit()
        flash("项目简介更新成功", "info")
        return redirect(url_for('main.show_all_projects'))

    return render_template("main/change-project.html", form=form, project=project)


# 修改文件简介
@main.route("/change-file/<file_id>", methods=["POST", "GET"])
@login_required
def change_file(file_id):
    form = ChangeFileForm()
    file = File.query.filter_by(id=file_id).first()
    if form.validate_on_submit():
        if form.new_origin_filename.data:
            file.origin_filename = form.new_origin_filename.data
        if form.new_description.data:
            file.description = form.new_description.data
        if form.new_author.data:
            file.author = form.new_author.data
        if form.new_reviewer.data:
            file.reviewer = form.new_reviewer.data
        db.session.commit()
        flash("文件信息修改成功", "success")
        return redirect(url_for('main.my_uploads'))

    return render_template("main/change-file.html", form=form, file=file)


# 删除文件
@main.route("/delete-file/<file_id>", methods=["GET", "POST"])
@fresh_login_required
def delete_file(file_id):
    file = File.query.filter_by(id=file_id).first()
    form = ConfirmDeleteForm()
    if form.validate_on_submit():
        try:
            os.remove(os.path.join(current_app.config['UPLOAD_PATH'], file.secure_filename))
            db.session.delete(file)
            db.session.commit()
            flash("指定文件已经被删除", "info")
            return redirect(url_for("main.show_all_projects"))
        except Exception as e:
            db.session.delete(file)
            db.session.commit()
            flash("文件已从数据库中被删除，但未找到文件本体，请联系网站作者", "warning")
            return redirect(url_for("main.show_all_projects"))

    return render_template("main/confirm-delete.html", form=form)


# 删除项目
@main.route("/delete-project/<project_id>", methods=["GET", "POST"])
@fresh_login_required
def delete_project(project_id):
    project = Project.query.filter_by(id=project_id).first()
    form = ConfirmDeleteForm()
    if form.validate_on_submit():
        # 删除项目下属的文件本体
        for each_file in project.its_files:
            os.remove(os.path.join(current_app.config['UPLOAD_PATH'], each_file.secure_filename))
        # 直接删除项目
        db.session.delete(project)
        db.session.commit()
        flash("指定项目及其所有文件已经被删除", "info")
        return redirect(url_for("main.show_all_projects"))

    return render_template("main/confirm-delete.html", form=form)


# 删除项目成员
@main.route("/delete-member/<project_id>/<user_id>", methods=["GET", "POST"])
@fresh_login_required
def delete_member(project_id, user_id):
    project = Project.query.filter_by(id=project_id).first()
    user = User.query.filter_by(id=user_id).first()
    form = ConfirmDeleteForm()
    if form.validate_on_submit():
        # 直接删除成员
        project.its_member_users.remove(user)
        db.session.commit()
        flash("用户已从项目组中删除", "info")
        return redirect(url_for("main.show_all_projects"))

    return render_template("main/delete-member.html", form=form)

leaf/templates/main/add_user.html
{% extends 'base.html' %}
{% block title %}添加成员{% endblock %}
{% block content %}

<!--当没有可添加的成员时，隐藏表单的Submit字段-->
<style>
    .hideme {
        display:none;
        }
</style>

<p><h6> 为 【{{ project.name }}】 添加成员</h6></p>

<form action="" method="post">
    {{ form.csrf_token }}
    <p>{{ form.member.label}}:</p>
    <p>{{ form.member }}</p>
    <p>{{ form.submit }}</p>
</form>
<p><small>提示：按住ctl键可以多选</small></p>

<a href="{{ url_for('main.project_detail', project_id=project.id) }}">返回项目详情页</a>
<hr>
<p><h6> 【{{ project.name }}】 现有成员列表</h6></p>

{% for user in project.its_member_users%}

    <p>{{user.name}}</p>

{% endfor %}

{% endblock %}

leaf/templates/main/change-file.html
{% extends 'base.html' %}
{% block title %}修改文件简介{% endblock %}
{% block content %}
<p><h6>修改文件简介</h6></p>
<br>

<form action="" method="post">
    {{ form.csrf_token }}

    <p>
        {{ form.new_origin_filename.label }} {{ form.new_origin_filename }}
        <small>现为：{{file.origin_filename}}</small>
    </p>
        {% for error in form.new_origin_filename.errors%}
             <p><strong>{{error}}</strong></p>
        {% endfor %}

    <p>
        {{ form.new_description.label }} {{ form.new_description }}
        <small>现为：{{file.description}}</small>
    </p>

    <p>
        {{ form.new_author.label }} {{ form.new_author }}
        <small>现为：{{file.author}}</small>
    </p>

    <p>
        {{ form.new_reviewer.label }} {{ form.new_reviewer }}
        <small>现为：{{file.reviewer}}</small>
    </p>

    <p>{{ form.submit }}</p>
</form>

<br>
<p><small>只输入你想修改的某几项信息即可</small></p>
<p><small>若不想改变某一项信息，在输入框中不输入任何字符</small></p>
{% endblock %}

leaf/templates/main/change-project.html
{% extends 'base.html' %}
{% block title %}修改项目{% endblock %}
{% block content %}
<p><h6>修改项目简介</h6></p>
<br>

<form action="" method="post">
    {{ form.csrf_token }}

    <p>
        {{ form.new_name.label }} {{ form.new_name }}
        <small>现为：{{project.name}}</small>
    </p>
        {% for error in form.new_name.errors%}
             <p><strong>{{error}}</strong></p>
        {% endfor %}

    <p>
        {{ form.new_description.label }} {{ form.new_description }}
        <small>现为：{{project.description}}</small>
    </p>

    <p>
        {{ form.new_start_time.label }} {{ form.new_start_time }}
        <small>现为：{{project.start_time}}</small>
    </p>

    <p>
        {{ form.new_end_time.label }} {{ form.new_end_time }}
        <small>现为：{{project.end_time}}</small>
    </p>

    <p>{{ form.submit }}</p>
</form>
<br>
<a href="{{ url_for('main.show_all_projects') }}">返回</a>
<br>
<p><small>只输入你想修改的某几项信息即可</small></p>
<p><small>若不想改变某一项信息，在输入框中不输入任何字符</small></p>
{% endblock %}

leaf/templates/main/confirm-delete.html
{% extends 'base.html' %}
{% block title %}确认删除{% endblock %}
{% block content %}
<p><h6>确认删除操作</h6></p>
<br>
<p>
<strong>警告：您正在执行删除操作，文件或项目一旦删除将无法回复。
    且删除项目将同时删除其所有文件。<br>
    请在下方输入您的登录密码以完成该敏感操作</strong>
</p>
<br>
<form action="" method="post">
    {{ form.csrf_token }}
    <p>
        {{ form.password.label }} {{ form.password }}
    </p>
        {% for error in form.password.errors%}
             <p><strong>{{error}}</strong></p>
        {% endfor %}
    <p>{{ form.submit }}</p>
</form>

<br>

{% endblock %}

leaf/templates/main/create_project.html
{% extends 'base.html' %}

{% block title %}新建{% endblock %}

{% block content %}
<p><h4>新建项目</h4></p>


<form method="post" action="">
    {{ form.csrf_token }}
    <p>{{ form.name.label }} {{ form.name }}</p>
        {% for error in form.name.errors %}
            {{ error }}
        {% endfor %}
    <p>{{ form.description.label }}</p>
    <p> {{ form.description }}</p>
        {% for error in form.description.errors %}
            {{ error }}
        {% endfor %}
    <small>
    <p>
        项目开始和结束日期请严格按照 "年-月-日"的格式填写，中间分隔符-为英文输入法的短横线。
    </p>
    <p>例如：2019-3-16 或 2019-11-3</p>
        </small>
    <p>{{ form.start_time.label }} {{ form.start_time }}
        {% for error in form.start_time.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </p>
    <p>{{ form.end_time.label }} {{ form.end_time }}
        {% for error in form.end_time.errors %}
            <small>{{ error }}</small>
        {% endfor %}
    </p>
    <p>{{ form.submit }}</p>
</form>

<p><small>注意：为了保证文件安全，项目创建成功后，只有系统管理员可以将其删除。普通用户只可以修改项目基本信息。</small></p>

{% endblock %}

leaf/templates/main/delete-member.html
{% extends 'base.html' %}
{% block title %}删除成员{% endblock %}
{% block content %}
<p><h6>删除成员</h6></p>
<br>
<p>
<strong>被删除的成员将不再能够操作项目或下载文件。<br>
    您也可以随时将其重新添加为项目组成员。<br>
    请在下方输入您的登录密码以完成该敏感操作</strong>
</p>
<br>
<form action="" method="post">
    {{ form.csrf_token }}
    <p>
        {{ form.password.label }} {{ form.password }}
    </p>
        {% for error in form.password.errors%}
             <p><strong>{{error}}</strong></p>
        {% endfor %}
    <p>{{ form.submit }}</p>
</form>

<br>

{% endblock %}

leaf/templates/main/index.html
{% extends 'base.html' %}

{% block title %}首页{% endblock %}

{% block content %}


<div class="container-fluid my-3">
  <div class="row">

    <div class="col-sm-4">
      <img src="../static/leaf.png" class="img-fluid" alt="Responsive image">
    </div>

    <div class="col-sm-8">
        <p><h1 class="text-success">欢迎来到LEAF！</h1></p>
        <h6 class="text-secondary">为跨团队协作而生的项目文档管理系统</h6>
        <p><h6 class="text-secondary">60秒上手，0遗漏通知，100%好用</h6></p>
    </div>

  </div>
</div>

<hr class="my-3">

<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
      现有项目共  <span class="badge badge-success">{{projects_sum}}</span> 个
    </div>
    <div class="col-sm">
      现有文件共  <span class="badge badge-success">{{files_sum}}</span> 个
    </div>
    <div class="col-sm">
      注册用户共  <span class="badge badge-success">{{ users_sum }}</span> 人
    </div>
  </div>
</div>

<hr class="my-3">
<div class="container-fluid">

    <p>最新动态：</p>
{% if latest_project %}
    <p>
        <strong><a class="text-primary" href="{{url_for('admin.profile', user_name=latest_project.its_creator.name)}}">{{latest_project.its_creator.name}}</a></strong>
        在 {{moment(latest_project.create_time).format('lll')}}
        创建了 <strong><a class="text-primary" href="{{ url_for('main.project_detail', project_id=latest_project.id ) }}">{{latest_project.name}}</a></strong>
    </p>

{% else %}
    <p class="text-muted">还没有建立任何项目</p>
{% endif %}

{% if latest_file %}
    <p>
        <strong><a class="text-primary" href="{{ url_for('admin.profile', user_name=latest_file.its_uploader.name ) }}">{{latest_file.its_uploader.name}}</a></strong>
        在 {{moment(latest_file.upload_time).format('lll')}}
        上传了 <strong><a class="text-primary" href="{{ url_for('main.project_detail', project_id=latest_file.its_project.id ) }}">{{latest_file.origin_filename}}</a></strong>
    </p>
{% else %}
    <p class="text-muted">还没有上传任何文件</p>
{% endif %}

</div>

{% endblock %}

leaf/templates/main/my_uploads.html
{% extends 'base.html' %}
{% block title %}我的上传{% endblock %}
{% block content %}
<p><h4>我的上传</h4></p>

{% if files %}

    <table border=1 cellpadding="15">
        <thead>
            <th>文件名称</th>
            <th>文件描述</th>
            <th>文件大小</th>
            <th>上传时间</th>
            <th>文件所属项目</th>
            <th>操作</th>
        </thead>
        <tbody>
            {% for item in files %}
            <tr>
                <td><a href="{{ url_for('main.project_detail', project_id=item.its_project.id) }}">{{ item.origin_filename }}</a></td>
                <td>{{ item.description }}</td>
                <td>{{ item.file_size | size}}</td>
                <td>{{ moment(item.upload_time).format('lll') }}</td>
                <td>{{ item.its_project.name }}</td>
                <td>
                    <p><a href="{{ url_for('main.change_file', file_id = item.id) }}">修改简介</a></p>
                    <a href="{{ url_for('main.delete_file', file_id=item.id) }}">删除文件</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    你还没有上传任何文件
{% endif %}

{% endblock %}

leaf/templates/main/project_detail.html
{% extends 'base.html' %}
{% block title %}详情{% endblock %}
{% block content %}
<p><h6>【{{ project.name }}】 成员列表</h6></p>
    {% if current_user.is_admin or current_user in project.its_member_users %}
        <p><small><a href="{{ url_for('main.add_user', project_id = project.id )}}">添加成员</a></small></p>
    {% else %}
        <p><small>只有本项目成员和系统管理员可以增减成员</small></p>
    {% endif %}
<table border="1" cellpadding="12">
    <thead>
        <th>姓名</th>
        <th>部门</th>
        <th>职务</th>
        <th>手机号</th>
        <th>邮箱</th>
        <th>身份</th>

        <!--只有系统管理员和项目创建人有权删除项目成员-->
        {% if current_user.is_admin or current_user.id == project.its_creator.id %}
        <th>成员操作</th>
        {% endif %}

    </thead>
    <tbody>
        {% for user in project.its_member_users %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.department }}</td>
            <td>{{ user.post }}</td>
            <td>{{ user.mobile }}</td>
            <td>{{ user.email }}</td>
            <td>
                {% if user.id == project.its_creator.id %}
                    项目创建人
                {% elif user.is_admin %}
                    系统管理员
                {% else %}
                    项目成员
                {% endif %}
            </td>

            <!--只有系统管理员和项目创建人有权删除项目成员-->
            <!--用户不能删除自己，也不能删除系统管理员-->
        {% if current_user.is_admin or current_user.id == project.its_creator.id %}
        <td>
            <small>
            {% if current_user.id == user.id %}
                不能删除自己
            {% elif user.is_admin %}
                管理员不能被删除
            {% else %}
            <a href="{{ url_for('main.delete_member', project_id=project.id, user_id=user.id) }}">删除成员</a>
            </small>
            {% endif %}
        </td>
        {% endif %}

        </tr>
        {% endfor %}
    </tbody>

</table>

<hr>
<p><h6>【{{ project.name }}】 所有文件</h6></p>
{% if current_user.is_admin or current_user in project.its_member_users %}
            <p><small><a href="{{ url_for('main.upload', project_id=project.id) }}">上传新文件</a></small></p>
        {% else %}
            <p><small>只有本项目成员和系统管理员可以上传文件</small></p>
        {% endif %}
<p><small>点击下列文件名即可下载</small></p>

<table border=1 cellpadding="8">
    <thead>
        <th>文件名</th>
        <th>文件大小</th>
        <th>文件描述</th>
        <th>上传人</th>
        <th>作者</th>
        <th>审核人</th>
        <th>上传时间</th>
        <th>操作</th>
    </thead>
    <tbody>
        {% for file in project.its_files %}
        <tr>
            <td><a href="{{ url_for('main.download', file_id=file.id) }}">{{ file.origin_filename }}</a></td>
            <td>{{ file.file_size | size}}</td>
            <td>{{ file.description }}</td>
            <td>{{ file.its_uploader.name }}</td>
            <td>{{ file.author }}</td>
            <td>{{ file.reviewer }} </td>
            <td>{{ moment(file.upload_time).format("lll") }}</td>

            <td>
                {% if current_user.is_admin or current_user.id == file.its_uploader.id %}
                <a href="{{ url_for('main.change_file', file_id = file.id) }}">修改简介</a>
                <br>
                <a href="{{ url_for('main.delete_file', file_id=file.id) }}">删除文件</a>
                {% else %}
                    只有文件上传人或系统管理员有权操作该文件
                {% endif %}
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

leaf/templates/main/show_all_projects.html
{% extends 'base.html' %}
{% block title %}总览{% endblock %}
{% block content %}
<p><h4>项目总览</h4></p>

{% if projects %}

<table class="table table-bordered table-sm">
    <thead class="thead-light">
        <th scope="col">名称</th>
        <th scope="col">描述</th>
        <th scope="col">创建人</th>
        <th scope="col">创建时间</th>
<!--        <th scope="col">开始时间</th>-->
<!--        <th scope="col">结束时间</th>-->
        <th scope="col">文件数</th>
        <th scope="col">成员数</th>
        <th scope="col">操作</th>
    </thead>
    <tbody>
        {% for item in projects %}
        <tr>
            <td><a href="{{ url_for('main.project_detail', project_id=item.id ) }}">{{ item.name }}</a></td>
            <td>{{ item.description }}</td>
            <td><a href="{{ url_for('admin.profile', user_name=item.its_creator.name ) }}">{{ item.its_creator.name }}</a></td>
            <td>{{ moment(item.create_time).format("ll") }}</td>
<!--            <td>{{ item.start_time }}</td>-->
<!--            <td>{{ item.end_time }}</td>-->
            <td> {{ item.its_files|count }}</td>
            <td>{{ item.its_member_users | count}}</td>
            <td>
                <small>

                <!--登录用户必须是项目组成员或Admin才能添加成员    -->
                {% if current_user.is_admin or current_user in item.its_member_users %}
                    <a href="{{ url_for('main.upload', project_id=item.id) }}">上传新文件/</a><br>
                    <a href="{{ url_for('main.add_user', project_id = item.id )}}">添加成员/</a><br>
                {% else %}
                    你不是本项目成员
                {% endif %}


                <!--登录用户必须是项目创建人或Admin才有下列2个选项-->
                {% if current_user.is_admin or current_user.id  == item.its_creator.id %}
                    <a href="{{ url_for('main.change_project', project_id=item.id)}}">修改项目简介</a><br>
                {% endif %}
                <!--登录用户必须是系统管理员Admin才能删除项目    -->
                {% if current_user.is_admin %}
                <a href="{{ url_for('main.delete_project', project_id=item.id) }}">/删除项目</a>
                {% endif %}
                </small>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
<p>空空如也，快去新建一个项目吧！</p>
{% endif %}

{% endblock %}

leaf/templates/main/upload.html
{% extends 'base.html' %}
{% block title %}上传文件{% endblock %}
{% block content %}
<p><h4>为 <strong>{{project.name}}</strong> 上传文件</h4></p>

<hr>

<form enctype="multipart/form-data" method="post" action="">
    {{ form.csrf_token }}
    <p>{{ form.file.label }} {{ form.file }}</p>
    <br>
    <p>{{ form.description.label }} {{ form.description }}</p>
    <p>{{ form.author.label }} {{ form.author }}</p>
    <p>{{ form.reviewer.label }} {{ form.reviewer }}</p>
    <p>{{ form.submit }}</p>
</form>
<p><a href="{{ url_for('main.project_detail', project_id=project.id) }}">返回项目详情页</a></p>

{% endblock %}